### ISSUE TITLE
[bug] Alert user when edited job has the same name.

### ISSUE THREAD

**Issue by guysoft** [guysoft/backupfriend-client#22]
See comment for:
https://github.com/guysoft/backupfriend-client/pull/18#issuecomment-835888737

There is an exception where a user dialog should appear.

**Comment by ygeyzel** [comment]
A user dialog is appearing.
The excption is catched at `AbstractJobDialog.save()` and handled by showing a message box to the user.

**Comment by guysoft** [comment]
Ok, will test and confirm.  Then close.  Thaks for the help!

**Comment by guysoft** [comment]
Ok, there is a bug.
If you click "edit" then "save". You get an error that the job you are saving already exists.
So it needs to discard itself.

Also English grammar and spelling errors I can fix :)

**Comment by guysoft** [comment]
Fixed
